async function audio(){if(!S?.sound)return false;let C=window.AudioContext||window.webkitAudioContext;if(!C)return false;if(!AC){AC=new C();MASTER=AC.createGain();COMP=AC.createDynamicsCompressor();REV=AC.createConvolver();MASTER.gain.value=.5;COMP.threshold.value=-20;COMP.ratio.value=5;let len=Math.floor(AC.sampleRate*1.1),buf=AC.createBuffer(2,len,AC.sampleRate);for(let ch=0;ch<2;ch++){let d=buf.getChannelData(ch);for(let i=0;i<len;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/len,2.7)}REV.buffer=buf;MASTER.connect(COMP);COMP.connect(AC.destination);REV.connect(MASTER)}if(AC.state!=='running')await AC.resume();return true}
function tone(f,d=.12,v=.08,type='triangle',wet=.1){audio().then(ok=>{if(!ok)return;let o=AC.createOscillator(),g=AC.createGain(),rg=AC.createGain(),t=AC.currentTime;o.frequency.value=f;o.type=type;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(v,t+.012);g.gain.exponentialRampToValueAtTime(.0001,t+d);rg.gain.value=wet;o.connect(g);g.connect(MASTER);g.connect(rg);rg.connect(REV);o.start();o.stop(t+d+.03)})}
function noiseBurst(){audio().then(ok=>{if(!ok)return;let n=Math.floor(AC.sampleRate*.18),buf=AC.createBuffer(1,n,AC.sampleRate),d=buf.getChannelData(0);for(let i=0;i<n;i++)d[i]=(Math.random()*2-1)*(1-i/n);let src=AC.createBufferSource(),g=AC.createGain();src.buffer=buf;g.gain.value=.08;src.connect(g);g.connect(MASTER);src.start()})}
function chord(a,d=.8,v=.016){a.forEach((f,i)=>setTimeout(()=>tone(f,d,v,i%2?'sine':'triangle',.18),i*18))}
function music(){if(MUS||!S?.sound)return;let seq=[[220,277,330],[196,247,294],[174,220,262],[247,311,370]],i=0;let p=()=>{let c=seq[i++%4];chord(c,1.55,.011);setTimeout(()=>tone(c[0]*2,.25,.011,'sine',.14),650)};p();MUS=setInterval(p,2100)}
function stop(){clearInterval(MUS);MUS=null}
function sfx(t){if(t==='good'){tone(660,.08,.065,'sine',.16);setTimeout(()=>tone(880,.11,.07,'triangle',.18),70);setTimeout(()=>tone(1320,.18,.045,'sine',.2),145)}else if(t==='bad'){noiseBurst();tone(150,.16,.085,'sawtooth',.04);setTimeout(()=>tone(90,.23,.07,'square',.03),80)}else if(t==='win'){[523,659,784,1046].forEach((f,i)=>setTimeout(()=>tone(f,.28,.055,'triangle',.2),i*90))}else if(t==='level'){chord([523,659,784],.45,.045);setTimeout(()=>chord([659,784,1046],.5,.04),220)}}
function fx(){let f=$('fx');if(!f){f=document.createElement('div');f.id='fx';f.className='fxlayer';document.body.appendChild(f)}return f}
function flash(good){let el=document.createElement('div');el.className='impactFlash'+(good?' goodFlash':'');document.body.appendChild(el);setTimeout(()=>el.remove(),520)}
function shake(){document.body.classList.remove('screen-shake');void document.body.offsetWidth;document.body.classList.add('screen-shake');setTimeout(()=>document.body.classList.remove('screen-shake'),380)}
function burst(kind='good',x=window.innerWidth/2,y=window.innerHeight*.35,label=''){let layer=fx();if(label){let l=document.createElement('div');l.className='particle label '+(kind==='bad'?'boom':'');l.textContent=label;l.style.cssText+=`;--x:${x}px;--y:${y}px;--dx:0px;--dy:-80px;--d:900ms;--s:28px;`;layer.appendChild(l);setTimeout(()=>l.remove(),950)}let icons=kind==='bad'?['💥','🔥','☄️','💣','⚡','🧨']:['🚀','✨','🌟','🎆','💫','🏆'];let n=kind==='bad'?18:22;for(let i=0;i<n;i++){let p=document.createElement('div');p.className='particle '+(kind==='bad'?'boom':'');p.textContent=icons[(Math.random()*icons.length)|0];let ang=Math.random()*Math.PI*2;let dist=(kind==='bad'?70:95)+Math.random()*(kind==='bad'?110:160);let dx=Math.cos(ang)*dist,dy=Math.sin(ang)*dist;let size=(kind==='bad'?18:20)+Math.random()*20;let dur=800+Math.random()*700;p.style.setProperty('--x',x+'px');p.style.setProperty('--y',y+'px');p.style.setProperty('--dx',dx+'px');p.style.setProperty('--dy',dy+'px');p.style.setProperty('--s',size+'px');p.style.setProperty('--d',dur+'ms');p.style.setProperty('--rot',((Math.random()*540)-270)+'deg');layer.appendChild(p);setTimeout(()=>p.remove(),dur+80)}flash(kind!=='bad');if(kind==='bad')shake()}
function centerBurst(kind,label){burst(kind,window.innerWidth/2,window.innerHeight*.33,label)}
function successFX(){centerBurst('good','¡Acierto!');sfx('good')}
function failFX(){centerBurst('bad','¡Fallo!');sfx('bad')}
function bossWinFX(){sfx('win');centerBurst('good','¡Victoria!');setTimeout(()=>centerBurst('good','País desbloqueado'),280);setTimeout(()=>burst('good',window.innerWidth*.25,window.innerHeight*.3),120);setTimeout(()=>burst('good',window.innerWidth*.75,window.innerHeight*.28),220)}
function bossFailFX(){sfx('bad');centerBurst('bad','Derrota');setTimeout(()=>burst('bad',window.innerWidth*.5,window.innerHeight*.38),120)}
function levelUpFX(){sfx('level');centerBurst('good','¡SUBES DE NIVEL!');setTimeout(()=>burst('good',window.innerWidth*.3,window.innerHeight*.28),120);setTimeout(()=>burst('good',window.innerWidth*.7,window.innerHeight*.28),220)}
